=== joinhud/EpamWebFirstTask/src/main/webapp/files/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/candies"
        xmlns:tns="http://www.epam.com/candies"
        elementFormDefault="qualified">
    <element name="candy" type="tns:CandyType" abstract="true"></element>
    <element name="sweet" type="tns:SweetType" substitutionGroup="tns:candy"></element>
    <element name="chocolate" type="tns:ChocolateType" substitutionGroup="tns:candy"></element>
    <element name="candies">
        <complexType>
            <sequence>
                <element ref="tns:candy" minOccurs="1" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="ChocolateType">
        <complexContent>
            <extension base="tns:CandyType">
                <sequence>
                    <element name="color" type="tns:ChocolateColor" />
                    <element name="ingredients" type="tns:ChocolateIngredients" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="ChocolateColor">
        <restriction base="string">
            <enumeration value="black"></enumeration>
            <enumeration value="white"></enumeration>
            <enumeration value="milk"></enumeration>
        </restriction>
    </simpleType>
    <complexType name="ChocolateIngredients">
        <sequence>
            <element name="cocoa-mass" type="tns:NumericValue" default="0" />
            <element name="sugar" type="tns:NumericValue" default="0" />
            <element name="cocoa-butter" type="tns:NumericValue" default="0" />
        </sequence>
    </complexType>
    <complexType name="SweetType">
        <complexContent>
            <extension base="tns:CandyType">
                <sequence>
                    <element name="type" type="tns:TypeOfSweet" />
                    <element name="ingredients" type="tns:SweetIngredients" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="TypeOfSweet">
        <restriction base="string">
            <enumeration value="lollipop"></enumeration>
            <enumeration value="chewing"></enumeration>
            <enumeration value="chocolate"></enumeration>
        </restriction>
    </simpleType>
    <complexType name="SweetIngredients">
        <sequence>
            <element name="water" type="tns:NumericValue" default="0" />
            <element name="sugar" type="tns:NumericValue" default="0" />
            <element name="fructose" type="tns:NumericValue" default="0" />
            <element name="vanilla" type="tns:NumericValue" default="0" />
        </sequence>
    </complexType>
    <complexType name="CandyType">
        <sequence>
            <element name="energy" type="tns:NumericValue" default="0"/>
            <element name="value" type="tns:Value"/>
            <element name="production" type="string"/>
        </sequence>
        <attribute name="name" type="tns:Name" use="required"/>
    </complexType>
    <simpleType name="Name">
        <restriction base="ID">
            <pattern value="[a-zA-Z]{2,50}"/>
        </restriction>
    </simpleType>
    <complexType name="Value">
        <sequence>
            <element name="proteins" type="tns:NumericValue" default="0"/>
            <element name="fats" type="tns:NumericValue" default="0"/>
            <element name="carbohydrates" type="tns:NumericValue" default="0"/>
        </sequence>
    </complexType>
    <simpleType name="NumericValue">
        <restriction base="decimal">
            <minInclusive value="0" />
        </restriction>
    </simpleType>
</schema>

=== joinhud/EpamWebFirstTask/src/main/webapp/files/candies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<candies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.com/candies"
        xsi:schemaLocation="http://www.epam.com/candies candies.xsd">
    <sweet name="RingPop">
        <energy>45</energy>
        <value>
            <proteins>0</proteins>
            <fats>0</fats>
            <carbohydrates>10</carbohydrates>
        </value>
        <production>Bazooka</production>
        <type>lollipop</type>
        <ingredients>
            <water>10</water>
            <sugar>0.50</sugar>
            <fructose>0.10</fructose>
            <vanilla>0</vanilla>
        </ingredients>
    </sweet>
    <chocolate name="AlpenGold">
        <energy>520</energy>
        <value>
            <proteins>0.56</proteins>
            <fats>0.28</fats>
            <carbohydrates>6.05</carbohydrates>
        </value>
        <production>ПАО Крафт Фудз Украина</production>
        <color>milk</color>
        <ingredients>
            <cocoa-mass>0.3</cocoa-mass>
            <sugar>0.6</sugar>
            <cocoa-butter>0.1</cocoa-butter>
        </ingredients>
    </chocolate>
</candies>
